/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'getting-started',
    {
      type: 'category',
      label: 'CLI',
      link: {type: 'doc', id: 'cli/hello-cli'},
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli',
        },

      ]
    },
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  tutorials: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
};

module.exports = sidebars;
